repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.3.0"
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: debug-statements
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: name-tests-test
      - id: trailing-whitespace

  - repo: https://github.com/asottile/pyupgrade
    rev: "v2.34.0"
    hooks:
      - id: pyupgrade
        args: ["--py310-plus"]

  - repo: https://github.com/asottile/add-trailing-comma
    rev: "v2.2.3"
    hooks:
      - id: add-trailing-comma

  - repo: https://github.com/asottile/yesqa
    rev: "v1.3.0"
    hooks:
    - id: yesqa

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: "v5.10.1"
    hooks:
      - id: isort

  - repo: https://github.com/psf/black
    rev: "22.3.0"
    hooks:
      - id: black

  - repo: local
    hooks:
      - id: flake8
        name: flake8
        entry: flake8
        language: python
        types: [python]
        require_serial: true

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: mypy
        language: python
        types_or: [python, pyi]
        require_serial: true

  - repo: https://github.com/jendrikseipp/vulture
    rev: "v2.4"
    hooks:
      - id: vulture

  - repo: https://github.com/PyCQA/bandit
    rev: "1.7.4"
    hooks:
      - id: bandit
