repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: ""
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: debug-statements
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: name-tests-test
      - id: trailing-whitespace

  - repo: https://github.com/asottile/pyupgrade
    rev: ""
    hooks:
      - id: pyupgrade
        args: ["--py310-plus"]

  - repo: https://github.com/asottile/add-trailing-comma
    rev: ""
    hooks:
      - id: add-trailing-comma

  - repo: https://github.com/asottile/yesqa
    rev: ""
    hooks:
    - id: yesqa

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: ""
    hooks:
      - id: isort

  - repo: https://github.com/psf/black
    rev: main
    hooks:
      - id: black

  - repo: local
    hooks:
      - id: flake8
        name: flake8
        entry: flake8
        language: python
        types: [python]
        require_serial: true

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: mypy
        language: system
        types_or: [python, pyi]
        args: ["--ignore-missing-imports", "--scripts-are-modules"]

  - repo: https://github.com/jendrikseipp/vulture
    rev: ""
    hooks:
      - id: vulture
        args: ["."]

  - repo: https://github.com/PyCQA/bandit
    rev: ""
    hooks:
      - id: bandit
        entry: bandit -r
        files: "."
