repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.3.0"
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: debug-statements
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: name-tests-test
      - id: trailing-whitespace

  - repo: local
    hooks:
      - id: pyupgrade
        name: pyupgrade
        entry: pyupgrade
        language: python
        types: [python]
        args: ["--py310-plus"]

      - id: add-trailing-comma
        name: Add trailing commas
        entry: add-trailing-comma
        language: python
        types: [python]

      - id: yesqa
        name: Strip unnecessary `# noqa`s
        entry: yesqa
        language: python
        types: [python]

      - id: isort
        name: isort
        entry: isort
        require_serial: true
        language: python
        language_version: python3
        types_or: [cython, pyi, python]
        args: ['--filter-files']

      - id: black
        name: black
        entry: black
        language: python
        minimum_pre_commit_version: 2.9.2
        require_serial: true
        types_or: [python, pyi]

      - id: flake8
        name: flake8
        entry: flake8
        language: python
        types: [python]
        require_serial: true

      - id: mypy
        name: mypy
        entry: mypy
        language: python
        types_or: [python, pyi]
        require_serial: true

      - id: vulture
        name: vulture
        language: python
        entry: vulture
        types: [python]
        pass_filenames: false
        require_serial: true

      - id: bandit
        name: bandit
        entry: bandit
        language: python
        language_version: python3
        types: [python]
        exclude: "{{ cookiecutter.bandit.exclude }}"
