
[tool.black]
line-length = 80

[tool.isort]
profile = "black"
line_length = 80
multi_line_output = 3

[tool.mypy]
disallow_untyped_defs = true
disallow_any_unimported = true
no_implicit_optional = true
check_untyped_defs = true
warn_return_any = true
show_error_codes = true
warn_unused_ignores = true

[[tool.mypy.overrides]]
module = "tasks"
disallow_any_unimported = false

[[tool.mypy.overrides]]
module = "invoke.*"
ignore_missing_imports = true

[tool.vulture]
min_confidence = 100

[tool.coverage.run]
branch = true
source = ["src/"]

[tool.coverage.report]
fail_under = 100
