[tool.mypy]
warn_redundant_casts = true
warn_unused_configs = true
warn_unused_ignores = true
{%- if cookiecutter.strict_level in ["low", "high"] %}
check_untyped_defs = true
disallow_untyped_defs = true
{%- endif %}
{%- if cookiecutter.strict_level == "high" %}
disallow_any_generics = true
disallow_incomplete_defs = true
disallow_subclassing_any = true
disallow_untyped_calls = true
disallow_untyped_decorators = true
no_implicit_optional = true
no_implicit_reexport = true
strict_concatenate = true
strict_equality = true
warn_return_any = true
{%- endif %}
