[tool.mypy]
check_untyped_defs = true
disallow_any_generics = true
disallow_incomplete_defs = true
disallow_subclassing_any = true
disallow_untyped_calls = true
disallow_untyped_decorators = true
disallow_untyped_defs = true
implicit_reexport = false
no_implicit_optional = true
show_error_codes = true
strict_concatenate = true
strict_equality = true
warn_redundant_casts = true
warn_return_any = true
warn_unused_configs = true
warn_unused_ignores = true

[[tool.mypy.overrides]]
module = "tasks"
disallow_any_unimported = false
disallow_untyped_decorators = false

[[tool.mypy.overrides]]
module = "invoke.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "tests.*"
disallow_any_unimported = false
disallow_untyped_decorators = false
