#!/bin/bash

poetry init -n --python '^3.10'

packages=(
    # formatting
    add-trailing-comma
    black
    isort
    # linting
    types-all
    flake8
    flake8-print
    pep8-naming
    mypy
    vulture
    bandit
    # testing
    pytest
    pytest-asyncio
    coverage
    # debug
    ipdb
    # make
    invoke
    # misc
    pre-commit
)
poetry add -D ${packages[@]}

mv pyproject.toml base_pyproject.toml
cat base_pyproject.toml tools_pyproject.toml > pyproject.toml
rm -f base_pyproject.toml tools_pyproject.toml

git init

poetry run pre-commit install
poetry run pre-commit autoupdate > /dev/null

curl \
    --location \
    --output .gitignore \
    https://www.toptal.com/developers/gitignore/api/python

git add .
git commit -m "Start project"
