repos:
  - repo: local
    hooks:
      - id: trailing-whitespace
        name: trim trailing whitespace
        entry: trailing-whitespace-fixer
        language: python
        types: [text]
        stages: [commit, push, manual]

      - id: end-of-file-fixer
        name: fix end of files
        entry: end-of-file-fixer
        language: python
        types: [text]
        stages: [commit, push, manual]

      - id: pyupgrade
        name: pyupgrade
        entry: pyupgrade
        language: python
        types: [python]
        args: ["--py310-plus"]

      - id: add-trailing-comma
        name: Add trailing commas
        entry: add-trailing-comma
        language: python
        types: [python]

      - id: yesqa
        name: Strip unnecessary `# noqa`s
        entry: yesqa
        language: python
        types: [python]

      - id: isort
        name: isort
        entry: isort
        require_serial: true
        language: python
        types_or: [cython, pyi, python]
        args: ["--filter-files"]

      - id: black
        name: black
        entry: black
        language: python
        require_serial: true
        types_or: [python, pyi]

      - id: check-ast
        name: check python ast
        entry: check-ast
        language: python
        types: [python]

      - id: debug-statements
        name: debug statements (python)
        entry: debug-statement-hook
        language: python
        types: [python]

      - id: name-tests-test
        name: python tests naming
        entry: name-tests-test
        language: python
        files: (^|/)tests/.+\.py$

      - id: check-merge-conflict
        name: check for merge conflicts
        entry: check-merge-conflict
        language: python
        types: [text]

      - id: check-added-large-files
        name: check for added large files
        entry: check-added-large-files
        language: python
        stages: [commit, push, manual]

      - id: detect-private-key
        name: detect private key
        entry: detect-private-key
        language: python
        types: [text]

      - id: flake8
        name: flake8
        entry: flake8
        language: python
        types: [python]
        require_serial: true

      - id: mypy
        name: mypy
        entry: mypy
        language: python
        types_or: [python, pyi]
        require_serial: true

      - id: vulture
        name: vulture
        language: python
        entry: vulture
        types: [python]
        require_serial: true

      - id: bandit
        name: bandit
        entry: bandit
        language: python
        types: [python]
        exclude: "tests/"
